import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    mainContainer:{
        backgroundColor:"#F9F7F7",
        flex:1,
    },
    HeaderContainer:{
        flexDirection:'row',
        justifyContent:'space-between'
    },
    HeaderBack:{
        padding:20,
        color:'#252A34',
        fontSize:24,
        fontWeight:'bold',
    },
    Header:{
        textAlign:'center',
        padding:20,
        color:'#252A34',
        fontSize:24,
        fontWeight:'bold',
    },
    HeaderComplete:{
        textAlign:'center',
        padding:20,
        color:'#252A34',
        fontSize:24,
        fontWeight:'bold',
        backgroundColor:'#f9f7f7'
    },
    contactPhotoContainer:{
        flexDirection:'row',
        justifyContent:'center'
    },
    personIcon:{
        padding:20,
        backgroundColor:'#252A34',
        borderRadius:50,
        fontSize:25,
        color:'#fff',
        margin:15,
    },
    nameContainer:{
        justifyContent:'center'
    },
    name:{
        backgroundColor:'#fff',
        marginHorizontal:20,
        marginVertical:10,
        borderRadius:10,
        paddingLeft:15,
    },
    ageContainer:{
        justifyContent:'center'
    },
    age:{
        backgroundColor:'#fff',
        marginHorizontal:20,
        marginVertical:10,
        borderRadius:10,
        paddingLeft:15,
    },
    errorvalidation:{
        color:'#252A34',
        marginHorizontal:20,
        marginVertical:10,
        borderRadius:10,
        paddingLeft:15,
        fontSize:9
    },
    image:{
        height:90,
        width:90,
        borderRadius:50,
    }
})