import {StyleSheet} from 'react-native'
export default StyleSheet.create({
    mainContainer:{
        backgroundColor:"#F9F7F7",
        flex:1,
    },
    Header:{
        textAlign:'center',
        color:'#252A34',
        fontSize:26,
        fontWeight:"bold",
        marginVertical:14,
    },
    containerEmpty:{
        flex:1,
        backgroundColor:'#F9F7F7',
        justifyContent: 'center',
    },
    emptyList:{
        textAlign:'center',
        color:'#252A34'
    },
    flatContainer:{
        flex:1
    },
    ContactListContainer:{
        flexDirection:'row',
        padding:20,
        marginHorizontal:15,
        marginVertical:10,
        backgroundColor:'#DBE2EF',
        borderRadius:30
    },
    imagePhoto:{
        width:50,   
        height:50,
        borderRadius:50,    
        alignSelf:'center', 
    },
    peopleIcon:{
        fontSize:27,
        color:'#f8ffff',
        padding:10,
        backgroundColor:'#3F72AF',
        borderRadius:50,
        textAlign:'center',
        alignSelf:'center', 
    },
    nameContactFirst:{
        fontSize:17,
        color:'#252A34',
        alignSelf:'center',
        marginLeft:15,
    },
    nameContactLast:{
        fontSize:17,
        color:'#252A34',
        alignSelf:'center',   
    },
    buttonContainer:{
        justifyContent:'flex-end',
        flexDirection:'row'
    },
    addButton:{
        fontSize:40,
        color:"#fff",
        backgroundColor:"#112D4E",
        padding:15,
        borderRadius:50,
        margin:7,
    }
})