import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    mainContainer:{
        flex:1,
        justifyContent:'center'
    },
    container:{
        justifyContent:'center',
        backgroundColor:'#205375',
        marginHorizontal:"10%",
        borderRadius:30,    
    },
    title:{
        color:'#F1EEE9',
        fontWeight:'bold',
        fontSize:27,
        textAlign:'center',
        marginVertical:20
    },
    personSection:{
        flexDirection:'row',
        justifyContent:'center'
    },
    personIcon:{
        color:'#F1EEE9',
        fontSize:40,
        padding:20,
        backgroundColor:'#EC994B',
        borderRadius:50,
    },
    inputSection:{
        flexDirection:'row',
        justifyContent:'center'
    },
    input:{
        backgroundColor:'#112B3C',
        width:'80%',
        color:'#F1EEE9',
        marginVertical:10,
        borderRadius:20,
        paddingLeft:10,
    },
    ButtonSection:{
        flexDirection:'row',
        justifyContent:'space-evenly'
    },
    button:{
        backgroundColor:'#EC994B',
        padding:15,
        fontSize:18,
        color:'#F1EEE9',
        fontWeight:'bold',
        marginVertical:10,
        borderRadius:30,
    },
    age:{
        color:'#F1EEE9',
        fontWeight:'bold',
        fontSize:18,
        alignSelf:'center'
    },
    inputSectionAge:{
        flexDirection:'row',
        justifyContent: 'space-evenly'
    },
    inputAge:{
        backgroundColor:'#112B3C',
        width:'25%',
        color:'#F1EEE9',
        marginVertical:10,
        borderRadius:20,
        textAlign:'center'
    },
    imagePhoto:{
        width:70,   
        height:70,
        borderRadius:50,    
        alignSelf:'center', 
    }

})