import {StyleSheet} from 'react-native'

export default StyleSheet.create({
    mainContainer:{
        backgroundColor:'#fff',
        flex:1
    },
    Header:{
        justifyContent:'center',
        flexDirection:'row'
    },
    HeaderText:{
        paddingVertical:12,
        color:'#333',
        fontSize:21,
        fontWeight:'bold'
    },
    searchbar:{
        flexDirection:'row',
        marginHorizontal:20,
        marginVertical:10,
        backgroundColor:'#DFDFDE',
        borderRadius:30,
    },
    searchIcon:{
        alignSelf:'center',
        color:'#383838',
        paddingLeft:20,
    },
    TextInputSearch:{
        flex:1,
        paddingLeft:5
    },
    clearIcon:{
        alignSelf:'center',
        textAlign:'center',
        color:'#383838',
        marginRight:10,
        backgroundColor:'#fff',
        padding:6,
        borderRadius:50,
    },
    bodyContainer:{
        flex:1,
    },
    AddContainer:{
        alignItems:'flex-end',
        flexDirection:'row',
        justifyContent:'flex-end'
    },
    addSection:{
        margin:20,
    },
    addIcon:{
        padding:15,
        textAlign:'center',
        color:'#fff',
        fontWeight:'bold',
        backgroundColor:'#383838',
        borderRadius:50,
    }
})