import { StyleSheet } from "react-native";

export default StyleSheet.create({
    mainContainer:{
    backgroundColor:'#fff',
    color:'#333',
    flex:1,
  },
  HeaderText:{
    fontSize:24,
    color:'#333',
    textAlign:'center',
    marginVertical:12,
    fontWeight:'bold',
  },
  body:{
    flex:1,
  },
  whileEmpty:{
    alignSelf:'center',
    color:'#333'
  },
  InputSection:{
    flexDirection:'row'
  },
  inputTextStyle:{
    backgroundColor:'#333',
    color:'#fff',
    marginVertical:10,
    fontSize:16,
    padding:17,
    marginHorizontal:12,
    width:'90%',
    borderRadius:40,
    paddingHorizontal:25,
  },
  addText:{
    width:70,
    color:'#fff',
    fontSize:35,
    padding:15,
    backgroundColor:'#333',
    borderRadius:50,
    marginVertical:10,
    textAlign:'center',
    alignSelf:'flex-end',
  },
  eachItem:{
      backgroundColor:'#333',
      marginVertical:6,
      marginHorizontal:15,
      borderRadius:50,
  },
  item:{
      padding:20,
      color:'white',
      fontSize:16,
      fontWeight:'500'
  }
})